language: python

dist: xenial
sudo: true

cache:
  directories:
    - $HOME/env

matrix:
  include:
    - python: 3.6
    - python: 3.7

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment
    - bash prepare_tests.sh

install:
    - pip install -U pip wheel
    - pip install -e .[tests,docs]

script:
    - py.test -v --cov-report= --cov=musdb tests/
    - cd docs; make html; touch html/.nojekyll

after_success:
    - coveralls
    
deploy:
  provider: pages
  skip_cleanup: false
  github_token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master
  local_dir: docs/html/