language: python
cache: pip
python:
    - 2.7
    - 3.5
before_install:
    - sudo apt-get update -qq
    - if [[ $TRAVIS_PYTHON_VERSION == *"2."* ]]; then sudo apt-get install python-numpy python-scipy; fi
    - if [[ $TRAVIS_PYTHON_VERSION == *"3."* ]]; then sudo apt-get install python3-numpy python3-scipy; fi
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
install:
    - pip install -U pip wheel
    - pip install -e .[tests,docs]
script:
    - py.test
    - python setup.py build_sphinx
    - python setup.py egg_info -b.dev sdist --formats gztar
