language: python

cache: pip

python:
    - "2.7_with_system_site_packages"
    - 3.4
    - 3.5

before_install:
    - sudo apt-get update -qq
    - if [[ $TRAVIS_PYTHON_VERSION == *"2."* ]]; then sudo apt-get install python-numpy; fi
    - if [[ $TRAVIS_PYTHON_VERSION == *"3."* ]]; then sudo apt-get install python3-numpy; fi
    - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
    - cd data
    - sh fetch.sh
    - cd ..

install:
    - pip install -U pip wheel
    - pip install -e .[tests,docs]
    - pip install python-coveralls

script:
    - py.test
    - python setup.py build_sphinx
    - python setup.py egg_info -b.dev sdist --formats gztar

after_success:
    - coveralls
