sample-url: https://zenodo.org/api/files/1ff52183-071a-4a59-923f-7a31c4762d43/MUSDB18-7-STEMS.zip

# Define the Input sources for each track
sources:
    vocals: vocals.wav
    drums: drums.wav
    bass: bass.wav
    other: other.wav

# Additionally provide the artistic mix
mixture:
    mixture.wav

stem_ids:
    mixture: 0
    drums: 1
    bass: 2
    other: 3
    vocals: 4

# Define output targets to be tested using linear mixtures
targets:
    vocals:
        vocals: 1
    drums:
        drums: 1
    bass:
        bass: 1
    other:
        other: 1
    accompaniment:
        bass: 1
        drums: 1
        other: 1
    linear_mixture:
        vocals: 1
        bass: 1
        drums: 1
        other: 1

validation_tracks:
    - 'Actions - One Minute Smile'
    - 'Clara Berry And Wooldog - Waltz For My Victims'
    - 'Johnny Lokke - Promises & Lies'
    - 'Patrick Talbot - A Reason To Leave'
    - 'Triviul - Angelsaint'
    - 'Alexander Ross - Goodbye Bolero'
    - 'Fergessen - Nos Palpitants'
    - 'Leaf - Summerghost'
    - 'Skelpolu - Human Mistakes'
    - 'Young Griffo - Pennies'
    - 'ANiMAL - Rockshow'
    - 'James May - On The Line'
    - 'Meaxic - Take A Step'
    - 'Traffic Experiment - Sirens'
